version: '3.8'

services:
  postgres:
    container_name: the_db
    image: postgres:latest
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432" # Expose to local? 
    volumes: 
      - pg-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  pg-data: